# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e1f486a35c6cebf507d6e65a19f05081f82d0406ae6aaf629788ebb9abda2b03a4a2f3fd19fee3f2f8f61b929ef1c5a46d2b7480223a7aba6e9145791d6aaf2

test:
  secret_key_base: 4793e2953d0bf0471c56dfe1de4660edf8638acd27e2dfc722f9c31a6a26862e8641f86ee76811cc2c7a6c8bb7d2ad15a5f853260428eb922f85e1808cfaa388

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
